apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: levelasquez/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: levelasquez/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: levelasquez/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: levelasquez/moderation
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: levelasquez/posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: levelasquez/query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
